global:
  scrape_interval: 15s

scrape_configs:
  # 1) NestJS-метрики (экспортирует prom-client)
  - job_name: 'user-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000'] # сервис бежит локально

  # 2) сам Prometheus (health)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
